name: Publish Maven Package

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/settings.xml'
      - '**/.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build artifact
      run: mvn clean install -DskipTests=true

    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: mvn deploy
        
